# GoChat 管理 & 调试工具
# 可选组件，用于方便地管理和调试核心基础设施

volumes:
  redis-insight-data:
    driver: local

services:
  kafka-ui:
    image: registry.cn-hangzhou.aliyuncs.com/gochat2025/provectuslabs-kafka-ui:latest
    container_name: gochat-kafka-ui
    hostname: kafka-ui
    restart: unless-stopped
    ports:
      - "8088:8080"
    networks:
      - infra-net
      - monitoring-net
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      KAFKA_CLUSTERS_0_NAME: gochat-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9092,kafka3:9092

  etcd-workbench:
    image: registry.cn-hangzhou.aliyuncs.com/gochat2025/tzfun-etcd-workbench:latest
    container_name: gochat-etcd-workbench
    hostname: etcd-workbench
    restart: unless-stopped
    ports:
      - "8002:8002"
    networks:
      - infra-net
      - monitoring-net
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    environment:
      ETCD_HOST: etcd1:2379,etcd2:2379,etcd3:2379

  redis-insight:
    image: registry.cn-hangzhou.aliyuncs.com/gochat2025/redis-redisinsight:latest
    container_name: gochat-redis-insight
    hostname: redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    networks:
      - infra-net
      - monitoring-net
    depends_on:
      - redis
    volumes:
      - redis-insight-data:/db

  phpmyadmin:
    image: registry.cn-hangzhou.aliyuncs.com/gochat2025/bitnami-phpmyadmin:latest
    container_name: gochat-phpmyadmin
    hostname: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: gochat_root_2024
      MYSQL_ROOT_PASSWORD: gochat_root_2024
    ports:
      - "8083:80"
    networks:
      - infra-net
      - monitoring-net
    depends_on:
      - mysql