# GoChat 基础设施部署配置
# 包含所有基础设施组件：etcd、kafka、mysql、redis 等
version: '3.8'

# 网络配置 - 分离不同类型的服务
networks:
  # 基础设施网络 - etcd、kafka、mysql、redis
  infra-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
  # 监控网络 - prometheus、grafana、管理界面
  monitoring-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16

# 数据卷配置 - 确保数据持久化
volumes:
  # etcd 数据卷
  etcd-data-1:
    driver: local
  etcd-data-2:
    driver: local
  etcd-data-3:
    driver: local
  # kafka 数据卷
  kafka-data-1:
    driver: local
  kafka-data-2:
    driver: local
  kafka-data-3:
    driver: local
  # mysql 数据卷
  mysql-data:
    driver: local
  # redis 数据卷
  redis-data:
    driver: local
  # redis-insight 数据卷
  redis-insight-data:
    driver: local
  # 监控数据卷
  prometheus-data:
  loki-data:
  grafana-data:

services:
  # ===== etcd 集群 =====
  etcd1:
    image: 'bitnami/etcd:3.5'
    container_name: gochat-etcd1
    hostname: etcd1
    restart: unless-stopped
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=gochat-etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_ENABLE_V2=true
    volumes:
      - etcd-data-1:/etcd-data
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - infra-net
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 10s
      retries: 3

  etcd2:
    image: 'bitnami/etcd:3.5'
    container_name: gochat-etcd2
    hostname: etcd2
    restart: unless-stopped
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=gochat-etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_ENABLE_V2=true
    volumes:
      - etcd-data-2:/etcd-data
    ports:
      - "2389:2379"
      - "2390:2380"
    networks:
      - infra-net
    depends_on:
      - etcd1
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 10s
      retries: 3

  etcd3:
    image: 'bitnami/etcd:3.5'
    container_name: gochat-etcd3
    hostname: etcd3
    restart: unless-stopped
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=gochat-etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_ENABLE_V2=true
    volumes:
      - etcd-data-3:/etcd-data
    ports:
      - "2399:2379"
      - "2400:2380"
    networks:
      - infra-net
    depends_on:
      - etcd1
      - etcd2
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ===== MySQL 数据库 =====
  mysql:
    image: mysql:8.0
    container_name: gochat-mysql
    hostname: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: gochat_root_2024
      MYSQL_DATABASE: gochat_dev
      MYSQL_USER: gochat
      MYSQL_PASSWORD: gochat_pass_2024
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - infra-net
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pgochat_root_2024"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ===== Redis 缓存 =====
  redis:
    image: redis:7-alpine
    container_name: gochat-redis
    hostname: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - infra-net
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ===== Kafka 集群 =====
  kafka1:
    image: 'bitnami/kafka:3.5'
    container_name: gochat-kafka1
    hostname: kafka1
    restart: unless-stopped
    ports:
      - "19092:9092"
    networks:
      - infra-net
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka-data-1:/bitnami/kafka

  kafka2:
    image: 'bitnami/kafka:3.5'
    container_name: gochat-kafka2
    hostname: kafka2
    restart: unless-stopped
    ports:
      - "29092:9092"
    networks:
      - infra-net
    depends_on:
      - kafka1
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka-data-2:/bitnami/kafka

  kafka3:
    image: 'bitnami/kafka:3.5'
    container_name: gochat-kafka3
    hostname: kafka3
    restart: unless-stopped
    ports:
      - "39092:9092"
    networks:
      - infra-net
    depends_on:
      - kafka1
      - kafka2
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka-data-3:/bitnami/kafka

  # ===== 监控 & 日志 =====
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: gochat-prometheus
    hostname: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - infra-net
      - monitoring-net
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  loki:
    image: grafana/loki:2.8.2
    container_name: gochat-loki
    hostname: loki
    restart: unless-stopped
    volumes:
      - ./config/loki/loki.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    ports:
      - "3100:3100"
    networks:
      - monitoring-net
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.8.2
    container_name: gochat-promtail
    hostname: promtail
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/promtail/promtail-config.yml:/etc/promtail/config.yml
    networks:
      - monitoring-net
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:9.5.3
    container_name: gochat-grafana
    hostname: grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=gochat_grafana_2024
    ports:
      - "3000:3000"
    networks:
      - monitoring-net

  # ===== 管理界面 =====
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: gochat-kafka-ui
    hostname: kafka-ui
    restart: unless-stopped
    ports:
      - "8088:8080"
    networks:
      - infra-net
      - monitoring-net
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      KAFKA_CLUSTERS_0_NAME: gochat-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9092,kafka3:9092

  etcd-workbench:
    image: tzfun/etcd-workbench:latest
    container_name: gochat-etcd-workbench
    hostname: etcd-workbench
    restart: unless-stopped
    ports:
      - "8002:8002"
    networks:
      - infra-net
      - monitoring-net
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    environment:
      ETCD_HOST: etcd1:2379,etcd2:2379,etcd3:2379

  redis-insight:
    image: redis/redisinsight:latest
    container_name: gochat-redis-insight
    hostname: redis-insight
    restart: unless-stopped
    ports:
      - "8001:8001"
    networks:
      - infra-net
      - monitoring-net
    depends_on:
      - redis
    volumes:
      - redis-insight-data:/db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: gochat-phpmyadmin
    hostname: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: gochat_root_2024
      MYSQL_ROOT_PASSWORD: gochat_root_2024
    ports:
      - "8083:80"
    networks:
      - infra-net
      - monitoring-net
    depends_on:
      - mysql
