# GoChat 核心基础设施
# 包含运行应用所必需的服务: etcd, kafka, mysql, redis
networks:
  infra-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  etcd-data-1:
    driver: local
  etcd-data-2:
    driver: local
  etcd-data-3:
    driver: local
  kafka-data-1:
    driver: local
  kafka-data-2:
    driver: local
  kafka-data-3:
    driver: local
  mysql-data:
    driver: local
  redis-data:
    driver: local

services:
  # ===== etcd 集群 =====
  etcd1:
    image: 'registry.cn-hangzhou.aliyuncs.com/gochat2025/bitnami-etcd:3.5.1'
    container_name: gochat-etcd1
    hostname: etcd1
    restart: unless-stopped
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=gochat-etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_ENABLE_V2=true
    volumes:
      - etcd-data-1:/etcd-data
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - infra-net
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 10s
      retries: 3

  etcd2:
    image: 'registry.cn-hangzhou.aliyuncs.com/gochat2025/bitnami-etcd:3.5.1'
    container_name: gochat-etcd2
    hostname: etcd2
    restart: unless-stopped
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=gochat-etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_ENABLE_V2=true
    volumes:
      - etcd-data-2:/etcd-data
    ports:
      - "2389:2379"
      - "2390:2380"
    networks:
      - infra-net
    depends_on:
      - etcd1
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 10s
      retries: 3

  etcd3:
    image: 'registry.cn-hangzhou.aliyuncs.com/gochat2025/bitnami-etcd:3.5.1'
    container_name: gochat-etcd3
    hostname: etcd3
    restart: unless-stopped
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=gochat-etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_ENABLE_V2=true
    volumes:
      - etcd-data-3:/etcd-data
    ports:
      - "2399:2379"
      - "2400:2380"
    networks:
      - infra-net
    depends_on:
      - etcd1
      - etcd2
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ===== MySQL 数据库 =====
  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/gochat2025/bitnami-mysql:8.0.39
    container_name: gochat-mysql
    hostname: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: gochat_root_2024
      MYSQL_DATABASE: gochat_dev
      MYSQL_USER: gochat
      MYSQL_PASSWORD: gochat_pass_2024
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - infra-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pgochat_root_2024"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ===== Redis 缓存 =====
  redis:
    image: registry.cn-hangzhou.aliyuncs.com/gochat2025/bitnami-redis:7.2.5
    container_name: gochat-redis
    hostname: redis
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - infra-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ===== Kafka 集群 =====
  kafka1:
    image: 'registry.cn-hangzhou.aliyuncs.com/gochat2025/bitnami-kafka:latest'
    container_name: gochat-kafka1
    hostname: kafka1
    restart: unless-stopped
    ports:
      - "19092:9092"
    networks:
      - infra-net
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka-data-1:/bitnami/kafka

  kafka2:
    image: 'registry.cn-hangzhou.aliyuncs.com/gochat2025/bitnami-kafka:latest'
    container_name: gochat-kafka2
    hostname: kafka2
    restart: unless-stopped
    ports:
      - "29092:9092"
    networks:
      - infra-net
    depends_on:
      - kafka1
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka-data-2:/bitnami/kafka

  kafka3:
    image: 'registry.cn-hangzhou.aliyuncs.com/gochat2025/bitnami-kafka:latest'
    container_name: gochat-kafka3
    hostname: kafka3
    restart: unless-stopped
    ports:
      - "39092:9092"
    networks:
      - infra-net
    depends_on:
      - kafka1
      - kafka2
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka-data-3:/bitnami/kafka