# etcd 集群独立部署配置
# 用于单独管理 etcd 集群的生命周期
version: '3.8'

networks:
  etcd-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16

volumes:
  etcd-data-1:
    driver: local
  etcd-data-2:
    driver: local
  etcd-data-3:
    driver: local

services:
  etcd1:
    image: 'bitnami/etcd:3.5'
    container_name: etcd1-standalone
    hostname: etcd1
    restart: unless-stopped
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-standalone
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_ENABLE_V2=true
      - ETCD_LOG_LEVEL=info
      - ETCD_AUTO_COMPACTION_MODE=periodic
      - ETCD_AUTO_COMPACTION_RETENTION=1h
    volumes:
      - etcd-data-1:/etcd-data
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      etcd-cluster:
        ipv4_address: 172.23.0.10
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health", "--endpoints=http://localhost:2379"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  etcd2:
    image: 'bitnami/etcd:3.5'
    container_name: etcd2-standalone
    hostname: etcd2
    restart: unless-stopped
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-standalone
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_ENABLE_V2=true
      - ETCD_LOG_LEVEL=info
      - ETCD_AUTO_COMPACTION_MODE=periodic
      - ETCD_AUTO_COMPACTION_RETENTION=1h
    volumes:
      - etcd-data-2:/etcd-data
    ports:
      - "2389:2379"
      - "2390:2380"
    networks:
      etcd-cluster:
        ipv4_address: 172.23.0.11
    depends_on:
      - etcd1
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health", "--endpoints=http://localhost:2379"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  etcd3:
    image: 'bitnami/etcd:3.5'
    container_name: etcd3-standalone
    hostname: etcd3
    restart: unless-stopped
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-standalone
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_ENABLE_V2=true
      - ETCD_LOG_LEVEL=info
      - ETCD_AUTO_COMPACTION_MODE=periodic
      - ETCD_AUTO_COMPACTION_RETENTION=1h
    volumes:
      - etcd-data-3:/etcd-data
    ports:
      - "2399:2379"
      - "2400:2380"
    networks:
      etcd-cluster:
        ipv4_address: 172.23.0.12
    depends_on:
      - etcd1
      - etcd2
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health", "--endpoints=http://localhost:2379"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # etcd 管理界面
  etcd-workbench:
    image: tzfun/etcd-workbench:latest
    container_name: my-etcd-workbench
    hostname: etcd-workbench
    restart: unless-stopped
    ports:
      - "8002:8002"
    networks:
      - etcd-cluster
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    environment:
      - ETCD_HOST=etcd1:2379,etcd2:2379,etcd3:2379
