# 存储服务部署配置
# 包含 MySQL 数据库和 Redis 缓存
version: '3.8'

networks:
  storage-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
  redis-insight-data:
    driver: local

services:
  # ===== MySQL 数据库 =====
  mysql:
    image: mysql:8.0
    container_name: mysql-standalone
    hostname: mysql
    restart: unless-stopped
    environment:
      # 基础配置
      MYSQL_ROOT_PASSWORD: gochat_root_2024
      MYSQL_DATABASE: gochat_dev
      MYSQL_USER: gochat
      MYSQL_PASSWORD: gochat_pass_2024
      # 字符集配置
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
      # 时区配置
      TZ: Asia/Shanghai
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts/mysql:/docker-entrypoint-initdb.d
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      storage-net:
        ipv4_address: 172.25.0.10
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=512M
      --innodb-log-file-size=256M
      --innodb-flush-log-at-trx-commit=2
      --innodb-flush-method=O_DIRECT
      --max-connections=200
      --max-allowed-packet=64M
      --query-cache-type=1
      --query-cache-size=64M
      --slow-query-log=1
      --slow-query-log-file=/var/log/mysql/slow.log
      --long-query-time=2
      --log-queries-not-using-indexes=1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pgochat_root_2024"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # ===== Redis 缓存 =====
  redis:
    image: redis:7-alpine
    container_name: redis-standalone
    hostname: redis
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    volumes:
      - redis-data:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      storage-net:
        ipv4_address: 172.25.0.11
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # ===== 管理界面 =====
  # MySQL 管理界面 (phpMyAdmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-standalone
    hostname: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: gochat_root_2024
      MYSQL_ROOT_PASSWORD: gochat_root_2024
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 64M
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 600
    ports:
      - "8083:80"
    networks:
      - storage-net
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis 管理界面 - RedisInsight
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight-standalone
    hostname: redis-insight
    restart: unless-stopped
    ports:
      - "8001:8001"
    networks:
      - storage-net
    depends_on:
      - redis
    volumes:
      - redis-insight-data:/data
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
