# im-repo 服务独立部署配置
version: '3.8'

networks:
  app-net:
    driver: bridge
  infra-net:
    external: true
    name: infrastructure_infra-net
  monitoring-net:
    external: true
    name: infrastructure_monitoring-net

services:
  im-repo:
    image: gochat/im-repo:latest
    container_name: im-repo-standalone
    hostname: im-repo
    restart: unless-stopped
    environment:
      # 应用基础配置
      - APP_ENV=dev
      - APP_NAME=im-repo
      - APP_VERSION=1.0.0
      - APP_DEBUG=true
      
      # 服务端口配置
      - HTTP_PORT=8080
      - GRPC_PORT=9000
      - METRICS_PORT=9091
      
      # 数据库配置
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=gochat_dev
      - DB_USER=gochat
      - DB_PASSWORD=gochat_pass_2024
      - DB_MAX_OPEN_CONNS=25
      - DB_MAX_IDLE_CONNS=10
      - DB_CONN_MAX_LIFETIME=1h
      - DB_CONN_MAX_IDLE_TIME=30m
      
      # Redis 缓存配置
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=
      - REDIS_POOL_SIZE=10
      - REDIS_MIN_IDLE_CONNS=5
      - REDIS_MAX_IDLE_CONNS=10
      
      # etcd 协调服务配置
      - ETCD_ENDPOINTS=etcd1:2379,etcd2:2379,etcd3:2379
      - ETCD_USERNAME=
      - ETCD_PASSWORD=
      - ETCD_TIMEOUT=5s
      
      # Kafka 消息队列配置
      - KAFKA_BROKERS=kafka1:9092,kafka2:9092,kafka3:9092
      - KAFKA_GROUP_ID=im-repo-group
      - KAFKA_AUTO_OFFSET_RESET=earliest
      
      # 监控和追踪配置
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      
      # 日志配置
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - LOG_OUTPUT=stdout
      
      # 健康检查配置
      - HEALTH_CHECK_INTERVAL=30s
      - HEALTH_CHECK_TIMEOUT=10s
      
    ports:
      - "8090:8080"  # HTTP API
      - "9000:9000"  # gRPC (如果需要)
      - "9091:9091"  # Prometheus Metrics
      
    networks:
      - app-net
      - infra-net
      - monitoring-net
      
    depends_on:
      - mysql
      - redis
      - etcd1
      - kafka1
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
      
    volumes:
      # 配置文件挂载
      - ./config/im-repo:/app/config:ro
      # 日志文件挂载
      - ./logs/im-repo:/app/logs
      # 临时文件挂载
      - ./tmp/im-repo:/app/tmp
      
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
          
    # 安全配置
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m