# Prometheus 配置文件 - GoChat 监控
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'gochat-dev'
    environment: 'development'

# 抓取配置
scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics