mysql:
  host: localhost
  port: 3306
  username: ceyewan
  password: 888666
  charset: utf8mb4

redis:
  addr: localhost:6379
  password: ""
  db: 0

logic_rpc:
  port: 8001
  
api_config:
  port: 8080

etcd:
  addrs:
    - localhost:23791
    - localhost:23792
    - localhost:23793

task_config:
  channelsize: 100