# GoChat 应用服务部署配置
# 遵循 KISS 原则，所有服务仅依赖 etcd 进行配置。
version: '3.8'

networks:
  gochat-net:
    name: deployment_infrastructure_gochat-net
    external: true

services:
  im-repo:
    image: gochat/im-repo:latest
    container_name: gochat-im-repo
    restart: unless-stopped
    networks:
      - gochat-net
    environment:
      - COORD_ETCD_ENDPOINTS=etcd1:2379,etcd2:2389,etcd3:2399
    ports:
      - "8090:8080" # HTTP API for health check or debug
      - "9091:9091" # Metrics
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  im-logic:
    image: gochat/im-logic:latest
    container_name: gochat-im-logic
    restart: unless-stopped
    networks:
      - gochat-net
    environment:
      - COORD_ETCD_ENDPOINTS=etcd1:2379,etcd2:2389,etcd3:2399
    ports:
      - "9000:9000" # gRPC
      - "9092:9092" # Metrics
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 3

  im-gateway:
    image: gochat/im-gateway:latest
    container_name: gochat-im-gateway
    restart: unless-stopped
    networks:
      - gochat-net
    environment:
      - COORD_ETCD_ENDPOINTS=etcd1:2379,etcd2:2389,etcd3:2399
    ports:
      - "8081:8080" # HTTP API
      - "8082:8081" # WebSocket
      - "9093:9093" # Metrics
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  im-task:
    image: gochat/im-task:latest
    container_name: gochat-im-task
    restart: unless-stopped
    networks:
      - gochat-net
    environment:
      - COORD_ETCD_ENDPOINTS=etcd1:2379,etcd2:2389,etcd3:2399
    ports:
      - "9094:9094" # Metrics
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9094/health"]
      interval: 30s
      timeout: 10s
      retries: 3